version: 0.0
os: linux

resources:
  - app:
      source: /TypeScript-Node-Starter
      destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/build_typescript.sh
      timeout: 300
      runas: root

