version: 0.2
env:
  variables:
    S3_BUCKET: "angular-site-first-12"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g typescript
      
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm prune --production
      
     
  post_build:
     commands:
      - aws s3 cp node_modules s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
     
    
      
artifacts:
  files:
      - '**/*'
   
  base-directory: 'dist*'
  discard-paths: yes
    
