version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build --if-present
  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
