version: 0.3

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g typescript
      - npm install

  pre_build:
    commands:
      - npm run build

  build:
    commands:
      - echo "Build phase"
      # Add any additional build commands here

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
